add images and change the two UIs
handsomeli0/Smart-Kiosk pull request #51
Opened 2022-04-07 14:32 UTC by quzhizhihou

2022-04-07 14:38 UTC, 2019213452 reviewed
ok

2022-04-07 14:40 UTC, 2019213452 approved these changes

2022-04-08 13:24 UTC, handsomeli0 requested changes
please change name of the rectangle.png

2022-04-08 13:46 UTC, 2019213452 approved these changes

2022-04-08 14:17 UTC, handsomeli0 approved these changes

2022-04-08 14:17 UTC, merged